### ISSUE TITLE
Install Stellarium on desktops

### ISSUE THREAD

**Issue by l0b0** [l0b0/root#52]
Package "stellarium"

**Comment by fincham** [comment]
+1 just because Stellarium is extremely cool :)

If you're doing Stellarium, add Gpredict too? http://gpredict.oz9aec.net/

**Comment by l0b0** [comment]
[Gpredict is only available through AUR](https://aur.archlinux.org/packages/gpredict/), and I haven't got the infrastructure to keep AUR packages up to date (Yaourt helps, but AUR packages are often really messy to install). If it becomes part of the official repos I'll add it.
